apiVersion: v1
kind: Secret
metadata:
  name: workervotacaosecret
type: Opaque
data:
  ConnectionAzureEventHubs: <STRING BASE 64>
  ConnectionAzureStorage: <STRING BASE 64>
  ConnectionSqlServer: <STRING BASE 64>



